#!/usr/bin/env bash
set -eu

DIST=www
BRANCH=gh-pages

[ -d "$DIST" ] || (echo "Directory '$DIST' not found."; exit 1)

echo 'Removing whatever is there'
git branch -D $BRANCH || true
git subtree split --prefix $DIST --branch $BRANCH

git push --no-verify origin $BRANCH --force
